CREATE TABLE `user` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `username` varchar(60) NOT NULL DEFAULT '' COMMENT '用户名',
  `parent_username` varchar(60) DEFAULT NULL COMMENT '来自那个用户',
  `depth` int(11) DEFAULT '0' COMMENT '深度',
  `list_progress_id` int(11) DEFAULT '0' COMMENT '采集用户索引进程ID',
  `list_uptime` int(10) DEFAULT NULL COMMENT '抓取索引时间',
  `list_server_id` tinyint(1) DEFAULT '0',
  `info_progress_id` int(11) DEFAULT '0' COMMENT '采集用户信息进程ID',
  `info_uptime` int(10) DEFAULT NULL COMMENT '抓取信息时间',
  `info_server_id` tinyint(1) DEFAULT '0',
  `nickname` varchar(32) NOT NULL COMMENT '真实姓名',
  `headimg` varchar(248) DEFAULT NULL COMMENT '头像',
  `location` varchar(32) DEFAULT NULL COMMENT '居住地',
  `business` varchar(32) DEFAULT NULL COMMENT '所在行业',
  `gender` tinyint(1) DEFAULT '2' COMMENT '性别 0:女 1:男 2:其他 ',
  `employment` varchar(32) DEFAULT NULL COMMENT '公司或组织名称',
  `position` varchar(32) DEFAULT NULL COMMENT '职位',
  `education` varchar(32) DEFAULT NULL COMMENT '学校或教育机构名',
  `education_extra` int(11) DEFAULT NULL COMMENT '专业方向',
  `weibo` varchar(248) DEFAULT NULL COMMENT '微博地址',
  `headline` varchar(248) DEFAULT NULL COMMENT '一句话介绍',
  `description` varchar(248) DEFAULT NULL COMMENT '个人简介',
  `last_message` varchar(248) DEFAULT NULL COMMENT '最后信息',
  `last_message_time` int(10) DEFAULT '0' COMMENT '最后信息时间',
  `last_message_week` tinyint(1) DEFAULT '7' COMMENT '最后信息星期，最大6，这里7做排除',
  `last_message_hour` tinyint(3) DEFAULT '24' COMMENT '最后信息小时，最大23，这里24做排除',
  `followees` int(11) DEFAULT '0' COMMENT '关注了',
  `followers` int(11) DEFAULT '0' COMMENT '关注者',
  `followed` int(11) DEFAULT '0' COMMENT '关注专栏',
  `topics` int(11) DEFAULT '0' COMMENT '关注话题',
  `pv` int(11) DEFAULT '0' COMMENT '主页被多少人浏览',
  `asks` int(11) DEFAULT '0' COMMENT '提问',
  `answers` int(11) DEFAULT '0' COMMENT '回答',
  `posts` int(11) DEFAULT '0' COMMENT '专栏文章',
  `collections` int(11) DEFAULT '0' COMMENT '收藏了',
  `logs` int(11) DEFAULT '0' COMMENT '公共编辑',
  `votes` int(11) DEFAULT '0' COMMENT '赞同',
  `thanks` int(11) DEFAULT '0' COMMENT '感谢',
  `favs` int(11) DEFAULT '0' COMMENT '收藏者',
  `shares` int(11) DEFAULT '0' COMMENT '分享',
  `birthday` date DEFAULT NULL COMMENT '生日',
  `status` tinyint(1) DEFAULT '0' COMMENT '状态',
  `addtime` int(10) DEFAULT NULL COMMENT '添加时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  KEY `location` (`location`),
  KEY `gender` (`gender`),
  KEY `business` (`business`),
  KEY `info_progress_id` (`info_progress_id`),
  KEY `education` (`education`),
  KEY `uptime` (`info_uptime`),
  KEY `index_time` (`list_uptime`),
  KEY `index_progress_id` (`list_progress_id`),
  KEY `last_message_week` (`last_message_week`),
  KEY `last_message_hour` (`last_message_hour`),
  KEY `list_server_id` (`list_server_id`),
  KEY `info_server_id` (`info_server_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
